### ISSUE TITLE
undefined: oauth2.RegisterBrokenAuthHeaderProvider

### ISSUE THREAD

**Issue by pavelz** [iris-contrib/plugin#3]
using example I get error trying to compile code.

```
../github.com/markbates/goth/providers/wepay/session.go:33: undefined: oauth2.RegisterBrokenAuthHeaderProvider
```

example from: http://iris-go.com/oauth_oauth2/

**Comment by kataras** [comment]
https://github.com/markbates/goth/blob/master/providers/wepay/session.go#L33 

"golang.org/x/oauth2" https://github.com/golang/oauth2 

Please upgrade the golang.org/x/oauth2 library
