### ISSUE TITLE
Oauth Gplus does not work

### ISSUE THREAD

**Issue by pavelz** [iris-contrib/plugin#4]
With current code base OAuth with GPlus does not work, I get "Not found" response as per example code that was implemented in the app when going to /oauth/gplus link.

commit 39f58fe286fe3f3344e3d62acdb333f8e9388b3a
Author: Gerasimos Maropoulos>
Date:   Wed Oct 5 18:42:52 2016 +0300

    Fix readme

commit d7946c45bab2d708475b52cb81c6e271e1b26faf
Author: Gerasimos Maropoulos 
Date:   Tue Sep 27 16:24:20 2016 +0300

    Update for v4.4.0

if you can provide guidance, how to rectify this. 
It used to work with 1 month old version of iris.

**Comment by pavelz** [comment]
so Handlers are not being invoked despite being registered into plugin/oauth.go at line 60: s.Get(...

**Comment by pavelz** [comment]
so far /oauth routes are registered but when they are registered with PreListen in Plugins they are not invoked.

**Comment by pavelz** [comment]
here is the API list from when plugin is done PreListen:

API: &{name:/search subdomain: method:[80 79 83 84] methodStr:POST path:/search middleware:[0x4003b20] formattedPath: formattedParts:0}
API: &{name:/count subdomain: method:[71 69 84] methodStr:GET path:/count middleware:[0x4003f60] formattedPath: formattedParts:0}
API: &{name:/ subdomain: method:[71 69 84] methodStr:GET path:/ middleware:[0x4004010] formattedPath: formattedParts:0}
API: &{name:/api/:id subdomain: method:[80 79 83 84] methodStr:POST path:/api/:id middleware:[0x4004820] formattedPath:/api/%v formattedParts:1}
API: &{name:/about subdomain: method:[71 69 84] methodStr:GET path:/about middleware:[0x4005030] formattedPath: formattedParts:0}
API: &{name:oauth subdomain: method:[71 69 84] methodStr:GET path:/oauth/:provider middleware:[0x407a140] formattedPath:/oauth/%v formattedParts:1}
API: &{name:/oauth/:provider/callback subdomain: method:[71 69 84] methodStr:GET path:/oauth/:provider/callback middleware:[0x407a390 0x40033e0] formattedPath:/oauth/%v/callback formattedParts:1}

**Comment by pavelz** [comment]
calls reach http get function, it seems there might be a bug here:

`// get is used by the Router, it finds and returns the correct muxEntry for a path
func (e *muxEntry) get(path string, _params PathParameters) (middleware Middleware, params PathParameters, mustRedirect bool) {
	fmt.Printf("ROUTE ACTION: %s %+v\n", path, _params)

	params = _params
loop:
	for {`

**Comment by pavelz** [comment]
it seems that PreListen route adds are not added to mux.lookups table one that is being used for routing from - Plugins. I suppose you can rebuild the lookup table after plugin init ?

**Comment by kataras** [comment]
PreListen was not the issue, the VHost was , that is fixed by introducing new event `PreBuild` which runs after configuration but before router builder and server up, as you pointed too. Please upgrade both plugin and iris and verify if that fixes the problem!
